# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rdaneel}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Edgar Gonzalez", "Anibal Rojas"]
  s.date = %q{2010-08-13}
  s.description = %q{Add robots.txt support on top of em-http-request}
  s.email = ["edgargonzalez@gmail.com", "anibalrojas@gmail.com"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rdaneel.rb",
     "spec/no_redirects_neither_robots_spec.rb",
     "spec/redirects_without_robots_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/streamed_content_spec.rb",
     "spec/using_cache_spec.rb"
  ]
  s.homepage = %q{http://github.com/hasmanydevelopers/RDaneel}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Obey robots.txt on top of em-http-request (Asynchronous HTTP Client)}
  s.test_files = [
    "spec/using_cache_spec.rb",
     "spec/no_redirects_neither_robots_spec.rb",
     "spec/spec_helper.rb",
     "spec/redirects_without_robots_spec.rb",
     "spec/streamed_content_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<em-http-request>, [">= 0.2.10"])
      s.add_runtime_dependency(%q<robot_rules>, [">= 0.9.3"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<em-http-request>, [">= 0.2.10"])
      s.add_dependency(%q<robot_rules>, [">= 0.9.3"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<em-http-request>, [">= 0.2.10"])
    s.add_dependency(%q<robot_rules>, [">= 0.9.3"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

